---
- name: "Create backend web app directory"
  file:
    path: ~/web
    state: directory

- name: "Copy backend artifact archive to server"
  template:
    src: "~/project/artifact.tar.gz"
    dest: "~/artifact.tar.gz"

- name: "Unpack backend artifact to web directory"
  unarchive:
    src: "~/project/artifact.tar.gz"
    dest: "~/web/"

- name: "Execute backend"
  shell: |
    pwd
    cd ~/web
    npm install
    pm2 stop default
    pm2 start npm -- start