---

- name: "Check env is set"
  shell: | 
    echo $PATH 
    echo $TYPEORM_HOST
    
- name: "Create backend web app directory"
  file:
    path: ~/udapeople-backend
    state: directory

# - name: "Copy backend artifact archive to server"
#   template:
#     src: "~/project/artifact.tar.gz"
#     dest: "~/artifact.tar.gz"

- name: "Unpack backend artifact from circleci container to ec2 server web directory"
  unarchive:
    src: "~/project/artifact.tar.gz"
    dest: "~/udapeople-backend/"

- name: "Check env is set"
  shell: | 
    echo $PATH 
    echo $TYPEORM_HOST
    
- name: "Execute backend"
  shell: |
    pwd
    cd ~/udapeople-backend
    npm install
    pm2 stop default
    pm2 start npm -- start