---
    
- name: "Create backend web app directory"
  file:
    path: ~/udapeople-backend
    state: directory

- name: "Unpack backend artifact from circleci container to ec2 server web directory"
  unarchive:
    src: "~/project/artifact.tar.gz"
    dest: "~/udapeople-backend/"

- name: "Execute backend"
  shell: |
    cd ~/udapeople-backend
    npm install
    pm2 stop default
    pm2 start npm -- start